### ISSUE TITLE
do not add git:// remotes only add git@... remotes

### ISSUE THREAD

**Issue by dimpase** [sagemath/sage_trac_plugin#18]
With trac running on GCE, one cannot use git:// for fetching, there were already a number of cases on sage-develop of this...
http://doc.sagemath.org/html/en/developer/git_trac.html
says that `git trac` adds the remotes automatically, although I don't see a place in the code where this is happening.

Is it really to blame on `git trac`, these `git://` URLs that break stuff?
Can this be fixed then?

**Comment by haraldschilly** [comment]
I don't know, but just to repeat some observation here again: maybe it's also a documentation issue? i.e. on the "the hard way" page, there is also a mention of the `git://` remote http://doc.sagemath.org/html/en/developer/manual_git.html#the-trac-server

**Comment by dimpase** [comment]
@haraldschilly that's right; actually, these instructions would be even simplified...

**Comment by vbraun** [comment]
git:// is anonymous access, and that worked until this weekend. Seems to me that there is an incorrect firewall rule on the GCE instance.

**Comment by dimpase** [comment]
there were reports on git:// not working before this weekend too.
I don't recall what exactly did happen then.

**Comment by vbraun** [comment]
I used it daily, it was definitely working

**Comment by dimpase** [comment]
IIRC after a complaint about it somebody quickly changed the ports
settings, opening the necessary port.

**Comment by embray** [comment]
This isn't really an issue for sage_trac_plugin which has nothing to do with git fetches.

**Comment by embray** [comment]
(That said, I'm not sure why git:// fetches aren't working; last I recall I made sure to enable them, but that has nothing to do with this Trac plugin).
